spring:
  batch:
    initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost/sample_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true